=== nguyenmanhhung2611/java-demo/testgit/source/webFrontPanaContents/webAdminPana/src/main/webapp/WEB-INF/mail/mail.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
	XML documents that conform to this DTD should declare the following doctype:
	<!DOCTYPE mail PUBLIC "-//OZACC//DTD MAIL//EN"
		"http://www.ozacc.com/library/dtd/ozacc-mail.dtd">
	
	$Id: mail.dtd,v 1.1 2007/02/13 07:29:34 ootsuka Exp $
-->

<!ELEMENT mail (returnPath?,from?,recipients?,replyTo?,errorTo?,xMailer?,subject?,body?,html?)>

<!ELEMENT from EMPTY>
<!ATTLIST from
	email CDATA #REQUIRED
	name CDATA #IMPLIED
>

<!ELEMENT replyTo EMPTY>
<!ATTLIST replyTo
	email CDATA #REQUIRED
>

<!ELEMENT errorTo EMPTY>
<!ATTLIST errorTo
	email CDATA #REQUIRED
>

<!ELEMENT xMailer (#PCDATA)>

<!ELEMENT returnPath EMPTY>
<!ATTLIST returnPath
	email CDATA #REQUIRED
>

<!ELEMENT recipients (to|cc|bcc)+>

<!ELEMENT to EMPTY>
<!ATTLIST to
	email CDATA #REQUIRED
	name CDATA #IMPLIED
>

<!ELEMENT cc EMPTY>
<!ATTLIST cc
	email CDATA #REQUIRED
	name CDATA #IMPLIED
>

<!ELEMENT bcc EMPTY>
<!ATTLIST bcc
	email CDATA #REQUIRED
>

<!ELEMENT subject (#PCDATA)>

<!ELEMENT body (#PCDATA)>

<!ELEMENT html (#PCDATA)>

=== nguyenmanhhung2611/java-demo/testgit/source/webAdminPana/src/main/webapp/WEB-INF/mail/sendAdminPassword.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${inputForm.email}" name="" />
    </recipients>
    <replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}" />

    <subject>新規パスワード発行完了のお知らせ</subject>

    <!-- Text body -->
    <body>
<![CDATA[

================================================================
新規パスワード発行完了のお知らせ
================================================================

$!{commonParameters.panasonicReSmail}管理画面において、新規パスワードの発行が
完了いたしました。

────────────────────────────────

■新パスワード
$!{inputForm.password}


◇管理システムへのログイン
$!{commonParameters.adminLoginUrl}

────────────────────────────────

以上、よろしくお願いいたします。


※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：$!{commonParameters.reSmailTel}
（受付時間　$!{commonParameters.reSmailUktskJkn}）
----------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
$!{commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


]]>
    </body>

</mail>

=== nguyenmanhhung2611/java-demo/testgit/webFrontPana/src/main/webapp/WEB-INF/mail/sendRequestUpdateLand.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${email}" name="" />
        <bcc email="${commonParameters.bccEmail}" />
    </recipients>
 	<replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>物件リクエスト登録内容変更のお知らせ[$!{housingRequestForm.housingRequestId}]</subject>

    <!-- Text body -->
    <body>
<![CDATA[

$!{commonParameters.panasonicReSmail}より、物件リクエストの登録内容を変更いただいたお客様に自動送信されています。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
物件リクエスト　ご登録内容変更完了のお知らせ
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

$!{commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

物件リクエストにご登録いただいている内容が変更されました。
本メールは、お客様の控えとして保管してください。
ご要望に合致する、または近い物件が見つかり次第、不動産会社担当者よりご連絡いたします。
また　ご要望内容に関して、ReaRie担当者より確認のご連絡をさせて頂く場合がございますので、ご承知おきの程宜しく御願い致します。

──変更いただいた物件リクエスト条件──────────────

■物件リクエスト番号
$!{housingRequestForm.housingRequestId}

■物件種別
$!{housingKindName}

■物件所在地
［都道府県］$!{prefName}
［市区町村］$!{addressName}
［沿線］ $!{rootName} $!{stationName}

■基本条件
［予算］$!{priceLower}${priceFromTo}$!{priceUpper}
［建物面積］$!{buildingAreaLower}${buildingFromTo}$!{buildingAreaUpper}
［土地面積］$!{landAreaLower}${landFromTo}$!{landAreaUpper}

◇物件リクエストの登録条件はマイページより確認・変更・削除いただけます。
${mypagePath}

────────────────────────────────

※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡ください。
※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：${commonParameters.reSmailTel}
（受付時間　${commonParameters.reSmailUktskJkn}）
----------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
${commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
]]>
    </body>

</mail>

=== nguyenmanhhung2611/java-demo/testgit/webCorePana/webAdminPana/src/main/webapp/WEB-INF/mail/sendInformation.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${inputForm.email}" name="" />
        <bcc email="${loginUserEmail}" />
    </recipients>
    <replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>【お知らせ更新】$!{inputForm.title}</subject>

    <!-- Text body -->
    <body>
<![CDATA[

${commonParameters.panasonicReSmail}より、会員登録をされているお客様へのお知らせです。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
お客様へのお知らせ
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

${commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

お客様へのお知らせが更新されました。
詳細はマイページよりご確認いただけます。

────────────────────────────────

■お知らせ件名
$!{inputForm.title}

以下のURLからお知らせの詳細をご確認ください。
${commonParameters.siteURL}/mypage/information/$!{inputForm.informationNo}/


◇その他のお知らせはマイページよりご確認ください。
${commonParameters.mypageLoginUrl}

────────────────────────────────


※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡ください。
※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：$!{commonParameters.reSmailTel}
（受付時間　${commonParameters.reSmailUktskJkn}）
------------------------------------------------------------------------
${commonParameters.panasonicReSmail}
$!{commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

]]>
    </body>

</mail>

=== nguyenmanhhung2611/java-demo/testgit/webAdminPanaContents/webAdminPana/src/main/webapp/WEB-INF/mail/sendMypagePassword.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${inputForm.email}" name="" />
        <bcc email="${commonParameters.bccEmail}" />
    </recipients>
    <replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>事務局より新規会員登録完了のお知らせ</subject>

    <!-- Text body -->
    <body>
<![CDATA[

$!{commonParameters.panasonicReSmail}より、新規会員登録いただいたお客様に自動送信されています。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
 　　　　　　新規会員登録完了のお知らせ
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

$!{commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

会員登録いただき、ありがとうございました。
お申し込みいただいた内容を元に、事務局にて手続きが完了いたしました。
ご登録内容はマイページよりご確認いただけます。

────────────────────────────────────

■パスワード
$!{inputForm.password}

■マイページログイン画面
$!{commonParameters.mypageLoginUrl}

※本メールが届いているメールアドレスと、上記に記載のパスワードでログインしてください。
※お名前、ご住所等の個人情報は、個人情報保護のため本メールには記載しておりません。

────────────────────────────────────

※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡ください。
※本メールは送信専用メールアドレスから配信されています。
　ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：$!{commonParameters.reSmailTel}
（受付時間　$!{commonParameters.reSmailUktskJkn}）
------------------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
 $!{commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


]]>
    </body>

</mail>

=== nguyenmanhhung2611/java-demo/testgit/source/webFrontPana/src/main/webapp/WEB-INF/mail/sendPasswordRemind.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${inputForm.email}" name="" />
    </recipients>
    <replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>パスワード再設定画面のご連絡</subject>

    <!-- Text body -->
    <body>
<![CDATA[

$!{commonParameters.panasonicReSmail}より、パスワードの再設定を希望されたお客様に自動送信されています。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
パスワード再設定のご連絡
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

$!{commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

下記のリンクより、新しいパスワードをご登録ください。

────────────────────────────────

■パスワード再設定用URL
$!{mailUrl}

※このリンクの有効期間は、URL発行時より24時間となります。
有効期間を過ぎてしまった場合には、恐れ入りますが再度「パスワードのお問い合わせ」よりお手続きください。

────────────────────────────────

※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡ください。
※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：${commonParameters.reSmailTel}
（受付時間　${commonParameters.reSmailUktskJkn}）
----------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
${commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

]]>
    </body>

</mail>

=== nguyenmanhhung2611/java-demo/testgit/source/webFrontPana/src/main/webapp/WEB-INF/mail/sendPasswordResult.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${inputForm.email}" name="" />
    </recipients>
    <replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>【重要】パスワード再設定完了のお知らせ</subject>

    <!-- Text body -->
    <body>
<![CDATA[

$!{commonParameters.panasonicReSmail}より、パスワードの再設定をされたお客様に自動送信されています。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
【重要】パスワード再設定完了のお知らせ
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

$!{commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

パスワードの再設定が完了いたしました。
下記よりマイページにログインいただけます。

────────────────────────────────

■マイページログイン画面
${mypageURL}

────────────────────────────────

引き続き、$!{commonParameters.panasonicReSmail}をどうぞよろしくお願いいたします。

※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡ください。
※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：${commonParameters.reSmailTel}
（受付時間　${commonParameters.reSmailUktskJkn}）
----------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
${commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


]]>
    </body>

</mail>

=== nguyenmanhhung2611/java-demo/testgit/source/webFrontPana/src/main/webapp/WEB-INF/mail/sendRequestDeleteLand.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${email}" name="" />
        <bcc email="${commonParameters.bccEmail}"/>
    </recipients>
 	<replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>物件リクエスト登録内容削除のお知らせ[$!{housingRequestForm.housingRequestId}]</subject>

    <!-- Text body -->
    <body>
<![CDATA[

$!{commonParameters.panasonicReSmail}より、物件リクエストの登録内容を削除いただいたお客様に自動送信されています。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
物件リクエスト　ご登録内容削除完了のお知らせ
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

$!{commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

物件リクエストにご登録いただいている内容が削除されました。
本メールは、お客様の控えとして保管してください。

──削除いただいた物件リクエスト条件──────────────


■物件リクエスト番号
$!{housingRequestForm.housingRequestId}

■物件種別
$!{housingKindName}

■物件所在地
［都道府県］$!{prefName}
［市区町村］$!{addressName}
［沿線］ $!{rootName} $!{stationName}

■基本条件
［予算］$!{priceLower}${priceFromTo}$!{priceUpper}
［建物面積］$!{buildingAreaLower}${buildingFromTo}$!{buildingAreaUpper}
［土地面積］$!{landAreaLower}${landFromTo}$!{landAreaUpper}

◇物件リクエストの登録条件はマイページより確認・変更・削除いただけます。
${mypagePath}

────────────────────────────────

※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡ください。
※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：${commonParameters.reSmailTel}
（受付時間　${commonParameters.reSmailUktskJkn}）
----------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
${commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
]]>
    </body>

</mail>

=== nguyenmanhhung2611/java-demo/testgit/source/webFrontPana/src/main/webapp/WEB-INF/mail/sendMemberInsert.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${inputForm.email}" name="" />
        <bcc email="${commonParameters.bccEmail}" />
    </recipients>
    <replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>新規会員登録完了のお知らせ</subject>

    <!-- Text body -->
    <body>
<![CDATA[

$!{commonParameters.panasonicReSmail}より、新規会員登録いただいたお客様に自動
送信されています。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
新規会員登録完了のお知らせ
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

$!{commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

会員登録いただき、ありがとうございました。
手続きが完了いたしました。
ご登録内容はマイページよりご確認いただけます。

────────────────────────────────

■ご登録いただいたメールアドレス
$!{inputForm.email}

■マイページログイン画面
$!{commonParameters.mypageLoginUrl}

※本メールアドレスと、会員登録の際に作成いただいたパスワードを
入力の上、ログインしてください。
※お名前、ご住所等の個人情報は、個人情報保護のため本メールには
記載しておりません。


────────────────────────────────

※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡
ください。
※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：$!{commonParameters.reSmailTel}
（受付時間　$!{commonParameters.reSmailUktskJkn}）
----------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
$!{commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


]]>
    </body>

</mail>
