=== nguyenmanhhung2611/java-demo/testgit/source/webFrontPanaContents/webAdminPana/src/main/webapp/WEB-INF/mail/mail.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
	XML documents that conform to this DTD should declare the following doctype:
	<!DOCTYPE mail PUBLIC "-//OZACC//DTD MAIL//EN"
		"http://www.ozacc.com/library/dtd/ozacc-mail.dtd">
	
	$Id: mail.dtd,v 1.1 2007/02/13 07:29:34 ootsuka Exp $
-->

<!ELEMENT mail (returnPath?,from?,recipients?,replyTo?,errorTo?,xMailer?,subject?,body?,html?)>

<!ELEMENT from EMPTY>
<!ATTLIST from
	email CDATA #REQUIRED
	name CDATA #IMPLIED
>

<!ELEMENT replyTo EMPTY>
<!ATTLIST replyTo
	email CDATA #REQUIRED
>

<!ELEMENT errorTo EMPTY>
<!ATTLIST errorTo
	email CDATA #REQUIRED
>

<!ELEMENT xMailer (#PCDATA)>

<!ELEMENT returnPath EMPTY>
<!ATTLIST returnPath
	email CDATA #REQUIRED
>

<!ELEMENT recipients (to|cc|bcc)+>

<!ELEMENT to EMPTY>
<!ATTLIST to
	email CDATA #REQUIRED
	name CDATA #IMPLIED
>

<!ELEMENT cc EMPTY>
<!ATTLIST cc
	email CDATA #REQUIRED
	name CDATA #IMPLIED
>

<!ELEMENT bcc EMPTY>
<!ATTLIST bcc
	email CDATA #REQUIRED
>

<!ELEMENT subject (#PCDATA)>

<!ELEMENT body (#PCDATA)>

<!ELEMENT html (#PCDATA)>

=== nguyenmanhhung2611/java-demo/testgit/webFrontPana/src/main/webapp/WEB-INF/mail/sendInquiryHousing.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${inputForm.getInquiryHeaderForm().email}" name="" />
        <bcc email="${commonParameters.bccEmail}" />
    </recipients>
    <replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>物件お問い合わせ内容の控え[$!{inputForm.inquiryId}]</subject>

    <!-- Text body -->
    <body>
<![CDATA[

$!{commonParameters.panasonicReSmail}より、物件のお問い合わせをいただいたお客様に自動送信されています。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
物件のお問い合わせ内容の控え
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

$!{commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

物件のお問い合わせをいただきありがとうございました。
本メールは、お客様の控えとして保管してください。
また　ご要望内容に関して、ReaRie担当者より確認のご連絡をさせて頂く場合がございますので、ご承知おきの程宜しく御願い致します。

──お問い合わせ内容──────────────────────────

■お問い合わせ番号
$!{inputForm.inquiryId}

■お問い合わせ物件
［物 件 番 号］ $!{inputForm.housingCd}

■お問い合わせ内容
［お問い合わせ内容］ $!{inputForm.inquiryDtlTypeMail}
［お問い合わせ内容詳細］ $!{inputForm.getInquiryHeaderForm().inquiryText}

※お名前、ご住所等の個人情報は、個人情報保護のため本メールには記載しておりません。

────────────────────────────────────

※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡ください。
※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：$!{commonParameters.reSmailTel}
（受付時間　$!{commonParameters.reSmailUktskJkn}）
------------------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
$!{commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

]]>
    </body>

</mail>

=== nguyenmanhhung2611/java-demo/testgit/webFrontPana/src/main/webapp/WEB-INF/mail/sendAssessmentInquiry.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mail PUBLIC "-//TC-DM3//DTD MAIL//EN" "mail.dtd">

<mail>
    <from email="${commonParameters.fromEmail}" name="${commonParameters.fromEmailName}" />
    <recipients>
        <to email="${inputForm.getInquiryHeaderForm().email}" name="" />
        <bcc email="${commonParameters.bccEmail}" />
    </recipients>
    <replyTo email="${commonParameters.replyToEmail}" />
    <errorTo email="${commonParameters.errorToEmail}"/>

    <subject>査定のお申し込み内容の控え[$!{inquiryId}]</subject>

    <!-- Text body -->
    <body>
<![CDATA[

$!{commonParameters.panasonicReSmail}より、査定のお申し込みをいただいたお客様
に自動送信されています。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
査定のお申し込み控え
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

$!{commonParameters.panasonicReSmail}をご利用いただきありがとうございます。

査定のお申し込みをいただきありがとうございました。
本メールは、お客様の控えとして保管してください。
また　ご要望内容に関して、ReaRie担当者より確認のご連絡をさせて頂く場合がございますので、ご承知おきの程宜しく御願い致します。

────────────────────────────────

■お問い合わせ番号
$!{inquiryId}

※ご売却物件所在地やお名前等の個人情報は、個人情報保護のため本
メールには記載しておりません。

────────────────────────────────

※本メールにお心当たりのないお客様は、お手数ですが下記までご連絡
ください。
※本メールは送信専用メールアドレスから配信されています。
ご返信いただいてもお答えできませんのでご了承ください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$!{commonParameters.panasonicReSmailAffairs}
問い合わせ先ナビダイヤル：$!{commonParameters.reSmailTel}
（受付時間　$!{commonParameters.reSmailUktskJkn}）
----------------------------------------------------------------
$!{commonParameters.panasonicReSmail}
$!{commonParameters.reSmailUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


]]>
    </body>

</mail>
